"""add relational ingestion schema

Revision ID: 51f31cbfb374
Revises: 
Create Date: 2026-09-15 03:48:53.259170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '51f31cbfb374'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('fetch_state', sa.String(length=32), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('next_fetch_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lease_owner', sa.String(length=255), nullable=True),
    sa.Column('lease_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_fetch_id', sa.UUID(), nullable=True),
    sa.Column('current_extraction_artifact_id', sa.UUID(), nullable=True),
    sa.Column('current_indexed_artifact_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("\n            (\n                fetch_state = 'leased'\n                AND lease_owner IS NOT NULL\n                AND lease_until IS NOT NULL\n            )\n            OR\n            (\n                fetch_state <> 'leased'\n                AND lease_owner IS NULL\n                AND lease_until IS NULL\n            )\n            ", name=op.f('ck_documents_lease_fields')),
    sa.CheckConstraint("fetch_state IN ('pending', 'leased', 'retry_wait', 'fetched', 'blocked')", name=op.f('ck_documents_fetch_state')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents'))
    )
    op.create_index('ix_documents_due', 'documents', ['next_fetch_at', 'id'], unique=False, postgresql_where=sa.text("fetch_state IN ('pending', 'retry_wait') AND next_fetch_at IS NOT NULL AND lease_until IS NULL"))
    op.create_index('ix_documents_lease_expiry', 'documents', ['lease_until', 'id'], unique=False, postgresql_where=sa.text('lease_until IS NOT NULL'))
    op.create_table('document_discoveries',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('source_key', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('source_config_version', sa.String(length=128), nullable=False),
    sa.Column('discovered_url', sa.String(length=2048), nullable=False),
    sa.Column('discovered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source_modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_document_discoveries_document_id_documents'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_discoveries'))
    )
    op.create_index('ix_document_discoveries_document_time', 'document_discoveries', ['document_id', sa.literal_column('discovered_at DESC')], unique=False)
    op.create_index('ix_document_discoveries_source_time', 'document_discoveries', ['source_key', sa.literal_column('discovered_at DESC')], unique=False)
    op.create_table('document_relations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source_document_id', sa.UUID(), nullable=False),
    sa.Column('target_document_id', sa.UUID(), nullable=False),
    sa.Column('relation_type', sa.String(length=32), nullable=False),
    sa.Column('verified', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("relation_type IN ('exact_content', 'near_duplicate', 'permanent_redirect', 'canonical')", name=op.f('ck_document_relations_relation_type')),
    sa.CheckConstraint('source_document_id <> target_document_id', name=op.f('ck_document_relations_different_documents')),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.id'], name=op.f('fk_document_relations_source_document_id_documents'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['target_document_id'], ['documents.id'], name=op.f('fk_document_relations_target_document_id_documents'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_relations')),
    sa.UniqueConstraint('source_document_id', 'target_document_id', 'relation_type', name='uq_document_relations_edge')
    )
    op.create_index('ix_document_relations_created_at', 'document_relations', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_document_relations_target_document_id', 'document_relations', ['target_document_id'], unique=False)
    op.create_table('document_urls',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('normalized_url', sa.String(length=2048), nullable=False),
    sa.Column('original_url', sa.String(length=2048), nullable=False),
    sa.Column('url_kind', sa.String(length=32), server_default=sa.text("'primary'"), nullable=False),
    sa.Column('verified', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("normalized_url ~ '^https?://'", name=op.f('ck_document_urls_normalized_url_http')),
    sa.CheckConstraint("original_url ~ '^https?://'", name=op.f('ck_document_urls_original_url_http')),
    sa.CheckConstraint("url_kind IN ('primary', 'redirect_alias', 'canonical_candidate')", name=op.f('ck_document_urls_url_kind')),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_document_urls_document_id_documents'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_urls')),
    sa.UniqueConstraint('normalized_url', name='uq_document_urls_normalized_url')
    )
    op.create_index('ix_document_urls_document_id', 'document_urls', ['document_id'], unique=False)
    op.create_table('stage_runs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('parent_run_id', sa.UUID(), nullable=True),
    sa.Column('stage_name', sa.String(length=64), nullable=False),
    sa.Column('stage_version', sa.String(length=128), nullable=False),
    sa.Column('config_version', sa.String(length=128), nullable=False),
    sa.Column('idempotency_key', sa.String(length=512), nullable=False),
    sa.Column('status', sa.String(length=32), server_default=sa.text("'queued'"), nullable=False),
    sa.Column('attempt', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('max_attempts', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lease_owner', sa.String(length=255), nullable=True),
    sa.Column('lease_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('input', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_category', sa.String(length=32), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("\n            (\n                status IN ('leased', 'running')\n                AND lease_owner IS NOT NULL\n                AND lease_until IS NOT NULL\n            )\n            OR\n            (\n                status NOT IN ('leased', 'running')\n                AND lease_owner IS NULL\n                AND lease_until IS NULL\n            )\n            ", name=op.f('ck_stage_runs_lease_fields')),
    sa.CheckConstraint("error_category IS NULL OR error_category IN ('retryable', 'permanent', 'blocked')", name=op.f('ck_stage_runs_error_category')),
    sa.CheckConstraint("status IN ('queued', 'leased', 'running', 'succeeded', 'retry_wait', 'failed', 'blocked', 'cancelled', 'skipped')", name=op.f('ck_stage_runs_status')),
    sa.CheckConstraint('attempt >= 0 AND max_attempts > 0 AND attempt <= max_attempts', name=op.f('ck_stage_runs_attempt_range')),
    sa.CheckConstraint('finished_at IS NULL OR started_at IS NULL OR finished_at >= started_at', name=op.f('ck_stage_runs_time_order')),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_stage_runs_document_id_documents'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_run_id'], ['stage_runs.id'], name=op.f('fk_stage_runs_parent_run_id_stage_runs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stage_runs')),
    sa.UniqueConstraint('idempotency_key', name='uq_stage_runs_idempotency_key')
    )
    op.create_index('ix_stage_runs_document_time', 'stage_runs', ['document_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_stage_runs_lease_expiry', 'stage_runs', ['lease_until', 'id'], unique=False, postgresql_where=sa.text('lease_until IS NOT NULL'))
    op.create_index('ix_stage_runs_retry_due', 'stage_runs', ['next_attempt_at', 'id'], unique=False, postgresql_where=sa.text("status IN ('queued', 'retry_wait') AND next_attempt_at IS NOT NULL"))
    op.create_table('artifacts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('producer_stage_run_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('schema_version', sa.String(length=128), nullable=False),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('object_key', sa.String(length=1024), nullable=False),
    sa.Column('content_type', sa.String(length=255), nullable=False),
    sa.Column('byte_size', sa.BigInteger(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("content_sha256 ~ '^[0-9a-f]{64}$'", name=op.f('ck_artifacts_content_sha256')),
    sa.CheckConstraint('byte_size >= 0', name=op.f('ck_artifacts_byte_size')),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_artifacts_document_id_documents'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['producer_stage_run_id'], ['stage_runs.id'], name=op.f('fk_artifacts_producer_stage_run_id_stage_runs'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_artifacts')),
    sa.UniqueConstraint('object_key', name='uq_artifacts_object_key')
    )
    op.create_index('ix_artifacts_document_kind', 'artifacts', ['document_id', 'kind'], unique=False)
    op.create_index('ix_artifacts_producer_stage_run_id', 'artifacts', ['producer_stage_run_id'], unique=False)
    op.create_table('document_fetches',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('document_url_id', sa.UUID(), nullable=False),
    sa.Column('stage_run_id', sa.UUID(), nullable=True),
    sa.Column('body_artifact_id', sa.UUID(), nullable=True),
    sa.Column('method', sa.String(length=16), server_default=sa.text("'GET'"), nullable=False),
    sa.Column('requested_url', sa.String(length=2048), nullable=False),
    sa.Column('final_url', sa.String(length=2048), nullable=True),
    sa.Column('outcome', sa.String(length=32), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('response_headers', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('etag', sa.String(length=1024), nullable=True),
    sa.Column('last_modified', sa.String(length=255), nullable=True),
    sa.Column('robots_policy_hash', sa.String(length=64), nullable=True),
    sa.Column('robots_allowed', sa.Boolean(), nullable=True),
    sa.Column('error_kind', sa.String(length=128), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("outcome IN ('succeeded', 'not_modified', 'http_error', 'transport_error', 'robots_denied', 'cancelled')", name=op.f('ck_document_fetches_outcome')),
    sa.CheckConstraint('completed_at IS NULL OR completed_at >= started_at', name=op.f('ck_document_fetches_time_order')),
    sa.CheckConstraint('status_code IS NULL OR status_code BETWEEN 100 AND 599', name=op.f('ck_document_fetches_status_code')),
    sa.ForeignKeyConstraint(['body_artifact_id'], ['artifacts.id'], name=op.f('fk_document_fetches_body_artifact_id_artifacts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_document_fetches_document_id_documents'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['document_url_id'], ['document_urls.id'], name=op.f('fk_document_fetches_document_url_id_document_urls'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['stage_run_id'], ['stage_runs.id'], name=op.f('fk_document_fetches_stage_run_id_stage_runs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_fetches'))
    )
    op.create_index('ix_document_fetches_document_time', 'document_fetches', ['document_id', sa.literal_column('started_at DESC')], unique=False)
    op.create_index('ix_document_fetches_stage_run_id', 'document_fetches', ['stage_run_id'], unique=False)
    op.create_foreign_key(
        'fk_documents_current_fetch_id_document_fetches',
        'documents',
        'document_fetches',
        ['current_fetch_id'],
        ['id'],
        ondelete='SET NULL',
    )
    op.create_foreign_key(
        'fk_documents_current_extraction_artifact_id_artifacts',
        'documents',
        'artifacts',
        ['current_extraction_artifact_id'],
        ['id'],
        ondelete='SET NULL',
    )
    op.create_foreign_key(
        'fk_documents_current_indexed_artifact_id_artifacts',
        'documents',
        'artifacts',
        ['current_indexed_artifact_id'],
        ['id'],
        ondelete='SET NULL',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'fk_documents_current_indexed_artifact_id_artifacts',
        'documents',
        type_='foreignkey',
    )
    op.drop_constraint(
        'fk_documents_current_extraction_artifact_id_artifacts',
        'documents',
        type_='foreignkey',
    )
    op.drop_constraint(
        'fk_documents_current_fetch_id_document_fetches',
        'documents',
        type_='foreignkey',
    )
    op.drop_index('ix_document_fetches_stage_run_id', table_name='document_fetches')
    op.drop_index('ix_document_fetches_document_time', table_name='document_fetches')
    op.drop_table('document_fetches')
    op.drop_index('ix_artifacts_producer_stage_run_id', table_name='artifacts')
    op.drop_index('ix_artifacts_document_kind', table_name='artifacts')
    op.drop_table('artifacts')
    op.drop_index('ix_stage_runs_retry_due', table_name='stage_runs', postgresql_where=sa.text("status IN ('queued', 'retry_wait') AND next_attempt_at IS NOT NULL"))
    op.drop_index('ix_stage_runs_lease_expiry', table_name='stage_runs', postgresql_where=sa.text('lease_until IS NOT NULL'))
    op.drop_index('ix_stage_runs_document_time', table_name='stage_runs')
    op.drop_table('stage_runs')
    op.drop_index('ix_document_urls_document_id', table_name='document_urls')
    op.drop_table('document_urls')
    op.drop_index('ix_document_relations_target_document_id', table_name='document_relations')
    op.drop_index('ix_document_relations_created_at', table_name='document_relations')
    op.drop_table('document_relations')
    op.drop_index('ix_document_discoveries_source_time', table_name='document_discoveries')
    op.drop_index('ix_document_discoveries_document_time', table_name='document_discoveries')
    op.drop_table('document_discoveries')
    op.drop_index('ix_documents_lease_expiry', table_name='documents', postgresql_where=sa.text('lease_until IS NOT NULL'))
    op.drop_index('ix_documents_due', table_name='documents', postgresql_where=sa.text("fetch_state IN ('pending', 'retry_wait') AND next_fetch_at IS NOT NULL AND lease_until IS NULL"))
    op.drop_table('documents')
    # ### end Alembic commands ###
