"""Export a trained PyTorch checkpoint as a dependency-free JavaScript module."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import torch


def tensor(value: torch.Tensor) -> list[object]:
    return value.detach().cpu().tolist()


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--checkpoint",
        type=Path,
        default=Path("../../data/learned_extraction/model/best.pt"),
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("src/model.generated.js"),
    )
    args = parser.parse_args()
    checkpoint = torch.load(args.checkpoint, map_location="cpu", weights_only=False)
    state = checkpoint["model_state"]
    preprocessing = checkpoint["preprocessing"]
    value = {
        "formatVersion": 1,
        "modelVersion": f"epoch-{checkpoint['epoch']}",
        "cleanupVersion": preprocessing["dom_cleanup"],
        "fields": checkpoint["fields"],
        "vocabulary": preprocessing["vocabulary"],
        "normalizer": preprocessing["normalizer"],
        "weights": {
            "missingScores": tensor(state["missing_scores"]),
            "tagEmbedding": tensor(state["tag_embedding.weight"]),
            "linear0": {
                "weight": tensor(state["network.0.weight"]),
                "bias": tensor(state["network.0.bias"]),
            },
            "linear1": {
                "weight": tensor(state["network.2.weight"]),
                "bias": tensor(state["network.2.bias"]),
            },
            "output": {
                "weight": tensor(state["network.4.weight"]),
                "bias": tensor(state["network.4.bias"]),
            },
        },
    }
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(
        "// Generated by scripts/export_checkpoint.py. Do not edit.\n"
        f"export default {json.dumps(value, separators=(',', ':'))};\n",
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
