"""Export the bundled base and author-boundary PyTorch weights to JavaScript."""

from __future__ import annotations

import argparse
import hashlib
import json
import struct
from pathlib import Path

import torch


def tensor(value: object) -> list[object]:
    if isinstance(value, torch.Tensor):
        return value.detach().cpu().tolist()
    return value.tolist()


def network(state: dict[str, torch.Tensor]) -> dict[str, object]:
    return {
        "linear0": {
            "weight": tensor(state["network.0.weight"]),
            "bias": tensor(state["network.0.bias"]),
        },
        "linear1": {
            "weight": tensor(state["network.2.weight"]),
            "bias": tensor(state["network.2.bias"]),
        },
        "output": {
            "weight": tensor(state["network.4.weight"]),
            "bias": tensor(state["network.4.bias"]),
        },
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--checkpoint", type=Path, required=True)
    parser.add_argument("--author-boundary", type=Path, required=True)
    parser.add_argument("--output", type=Path, default=Path("src/model.generated.js"))
    args = parser.parse_args()
    checkpoint_bytes = args.checkpoint.read_bytes()
    checkpoint = torch.load(args.checkpoint, map_location="cpu", weights_only=False)
    boundary = torch.load(args.author_boundary, map_location="cpu", weights_only=False)
    digest = hashlib.sha256(checkpoint_bytes).hexdigest()
    if boundary["base_sha256"] != digest:
        raise ValueError("author boundary weights do not match the base checkpoint")
    state = checkpoint["model_state"]
    value = {
        "formatVersion": 2,
        "modelVersion": f"epoch-{checkpoint['epoch']}+{boundary['version']}",
        "checkpointSha256": digest,
        "cleanupVersion": checkpoint["preprocessing"]["dom_cleanup"],
        "featureVersion": checkpoint["preprocessing"]["feature_version"],
        "fields": checkpoint["fields"],
        "vocabulary": checkpoint["preprocessing"]["vocabulary"],
        "semanticVocabulary": checkpoint["preprocessing"]["semantic_vocabulary"],
        "normalizer": checkpoint["preprocessing"]["normalizer"],
        "weights": {
            "missingScores": tensor(state["missing_scores"]),
            "tagEmbedding": tensor(state["tag_embedding.weight"]),
            "semanticEmbedding": tensor(state["semantic_embedding.weight"]),
            **network(state),
        },
        "authorBoundary": {
            "version": boundary["version"],
            "mean": tensor(boundary["mean"]),
            "std": tensor(boundary["std"]),
            "changeMargin": float(boundary["change_margin"]),
            "linear0": {
                "weight": tensor(boundary["model_state"]["network.0.weight"]),
                "bias": tensor(boundary["model_state"]["network.0.bias"]),
            },
            "output": {
                "weight": tensor(boundary["model_state"]["network.2.weight"]),
                "bias": tensor(boundary["model_state"]["network.2.bias"]),
            },
        },
    }
    binary = bytearray()

    def compact(array: object) -> object:
        if isinstance(array, list) and array and all(isinstance(row, list) for row in array):
            width = len(array[0])
            if all(len(row) == width and all(isinstance(item, (int, float)) for item in row) for row in array):
                flattened = [item for row in array for item in row]
                offset = len(binary) // 4
                binary.extend(struct.pack(f"<{len(flattened)}f", *flattened))
                return {"f32": [offset, len(array), width]}
        if isinstance(array, list) and array and all(isinstance(item, (int, float)) for item in array):
            offset = len(binary) // 4
            binary.extend(struct.pack(f"<{len(array)}f", *array))
            return {"f32": [offset, len(array)]}
        if isinstance(array, dict):
            return {key: compact(item) for key, item in array.items()}
        return array

    value["weights"] = compact(value["weights"])
    value["authorBoundary"] = compact(value["authorBoundary"])
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.with_name("model.weights.bin").write_bytes(binary)
    args.output.write_text(
        "// Generated by scripts/export_checkpoint.py. Do not edit.\n"
        'import { readFileSync } from "node:fs";\n'
        'const bytes = readFileSync(new URL("./model.weights.bin", import.meta.url));\n'
        'const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength);\n'
        'function hydrate(value) {\n'
        '  if (value && typeof value === "object" && "f32" in value) {\n'
        '    const [offset, rows, columns] = value.f32;\n'
        '    const numbers = Array.from({ length: rows * (columns ?? 1) }, (_, i) => view.getFloat32((offset + i) * 4, true));\n'
        '    return columns === undefined ? numbers : Array.from({ length: rows }, (_, i) => numbers.slice(i * columns, (i + 1) * columns));\n'
        '  }\n'
        '  if (Array.isArray(value)) return value.map(hydrate);\n'
        '  if (value && typeof value === "object") return Object.fromEntries(Object.entries(value).map(([key, item]) => [key, hydrate(item)]));\n'
        '  return value;\n'
        '}\n'
        f"export default hydrate({json.dumps(value, separators=(',', ':'))});\n",
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
